# Reads supabase/.env.local and builds a client with only the public Supabase
# URL and publishable key. Storage secrets in that file are never copied.
param(
    [Parameter(Position = 0)]
    [ValidateSet('apk', 'appbundle', 'windows', 'ios', 'run-android', 'run-windows', 'admin', 'sync')]
    [string]$Target = 'apk',

    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ExtraArgs
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $repoRoot 'supabase\.env.local'
$flutterConfig = Join-Path $repoRoot 'app\config\local.json'
$adminEnv = Join-Path $repoRoot 'admin\.env.local'

function Read-DotEnv {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Missing $Path. Add the public Supabase values there before building."
    }

    $map = @{}
    foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('#')) {
            continue
        }
        $separator = $trimmed.IndexOf('=')
        if ($separator -lt 1) {
            continue
        }
        $name = $trimmed.Substring(0, $separator).Trim()
        $value = $trimmed.Substring($separator + 1).Trim()
        if (
            ($value.StartsWith('"') -and $value.EndsWith('"')) -or
            ($value.StartsWith("'") -and $value.EndsWith("'"))
        ) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $map[$name] = $value
    }
    return $map
}

function Require-PublicValue {
    param($Map, [string]$Name)
    if (-not $Map.ContainsKey($Name) -or [string]::IsNullOrWhiteSpace($Map[$Name])) {
        throw "$Name is missing from supabase/.env.local."
    }
    return $Map[$Name].Trim()
}

$envMap = Read-DotEnv -Path $envFile
$url = Require-PublicValue -Map $envMap -Name 'SUPABASE_URL'
$key = Require-PublicValue -Map $envMap -Name 'SUPABASE_PUBLISHABLE_KEY'

if (-not $url.StartsWith('https://')) {
    throw 'SUPABASE_URL in supabase/.env.local must start with https://.'
}
if ($key.StartsWith('sb_secret') -or $key.Contains('service_role')) {
    throw 'Refusing to put a service key into a client build. Use the publishable key.'
}

$utf8 = New-Object System.Text.UTF8Encoding $false
$flutterJson = (@{
        SUPABASE_URL             = $url
        SUPABASE_PUBLISHABLE_KEY = $key
    } | ConvertTo-Json)
[System.IO.File]::WriteAllText($flutterConfig, $flutterJson + "`n", $utf8)

$adminText = @(
    '# Generated by scripts/build.ps1 from supabase/.env.local.'
    '# Only the public Supabase values are copied. Do not add storage secrets.'
    "VITE_SUPABASE_URL=$url"
    "VITE_SUPABASE_PUBLISHABLE_KEY=$key"
) -join "`n"
[System.IO.File]::WriteAllText($adminEnv, $adminText + "`n", $utf8)

Write-Host 'Public Supabase config refreshed from supabase/.env.local.'

if ($Target -eq 'sync') {
    exit 0
}

if ($Target -eq 'admin') {
    Push-Location (Join-Path $repoRoot 'admin')
    try {
        & npm run build
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }
    finally {
        Pop-Location
    }
    exit 0
}

$flutterCommand = switch ($Target) {
    'apk' { @('build', 'apk', '--release') }
    'appbundle' { @('build', 'appbundle', '--release') }
    'windows' { @('build', 'windows', '--release') }
    'ios' { @('build', 'ios', '--release') }
    'run-android' { @('run', '-d', 'android') }
    'run-windows' { @('run', '-d', 'windows') }
}

Push-Location (Join-Path $repoRoot 'app')
try {
    & flutter @flutterCommand --dart-define-from-file=config/local.json @ExtraArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}
finally {
    Pop-Location
}
